\set ON_ERROR_STOP on
begin;
create function pg_temp.assert(ok boolean,msg text) returns void language plpgsql as $$ begin if not coalesce(ok,false) then raise exception 'Assertion failed: %',msg; end if; end $$;
do $$ declare req jsonb; q jsonb; o jsonb; oid uuid; pid uuid; stock_before integer; n integer; failed boolean; ing uuid; actor uuid:='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; d jsonb; begin
insert into auth.users(id) values(actor); insert into profiles(id,role) values(actor,'admin');
d:=jsonb_build_object('name','Test Guest','phone','923009999999','method','delivery','area','Gulshan','address','Fictional test address','event_date',(current_date+14)::text,'delivery_window','3pm – 6pm','event_type','Birthday');
req:=submit_request(d,'request-upload-test'); perform pg_temp.assert(submit_request(d,'request-upload-test')=req,'request retry is idempotent'); perform pg_temp.assert(req->>'number' like 'CCR-%','request number'); perform pg_temp.assert((select status='new_inquiry' from custom_cake_requests where id=(req->>'id')::uuid),'request is not confirmed');
q:=create_quote(jsonb_build_object('request_id',req->>'id','price',5000,'delivery_fee',350,'discount',500,'advance',2500,'notes','Test','feasible',true,'suggested_changes','','expires_at',now()+interval '1 day','status','sent'),'test-token-hash');
perform pg_temp.assert(q->>'number' like 'CCQ-%','quotation number');
o:=decide_quote('test-token-hash','accepted');oid:=(o->>'order_id')::uuid;
perform pg_temp.assert((select status='awaiting_advance' from orders where id=oid),'accepted quote awaits advance');
failed:=false;begin perform decide_quote('test-token-hash','accepted');exception when others then failed:=true;end;perform pg_temp.assert(failed,'cannot accept twice');
failed:=false;begin perform transition_order(oid,'confirmed',actor,null);exception when others then failed:=true;end;perform pg_temp.assert(failed,'unpaid confirmation blocked');
insert into payments(order_id,amount,method,type) values(oid,2500,'bank_transfer','advance') returning id into pid;
failed:=false;begin perform transition_order(oid,'confirmed',actor,null);exception when others then failed:=true;end;perform pg_temp.assert(failed,'pending proof does not confirm');
perform verify_payment(pid,actor);perform pg_temp.assert((select verified_by=actor and verified_at is not null from payments where id=pid),'payment verifier audit');
perform transition_order(oid,'confirmed',actor,null);perform transition_order(oid,'in_preparation',actor,null);perform transition_order(oid,'ready',actor,null);perform transition_order(oid,'delivered',actor,null);perform transition_order(oid,'completed',actor,null);
perform pg_temp.assert((select count(*)=6 from order_status_history where order_id=oid),'timestamped status history');perform pg_temp.assert((select completed_at is not null from orders where id=oid),'completion date');
insert into expenses(category,amount,order_id,allocation) values('Packaging',100,oid,'packaging_cost'); perform pg_temp.assert((select packaging_cost=100 from orders where id=oid),'expense allocation updates direct costs');
select stock into stock_before from products where id='00000000-0000-4000-8000-000000000001';
failed:=false;begin perform checkout(d,'[{"id":"00000000-0000-4000-8000-000000000001","quantity":999}]','overstock');exception when others then failed:=true;end;perform pg_temp.assert(failed,'stock oversell blocked');perform pg_temp.assert((select stock=stock_before from products where id='00000000-0000-4000-8000-000000000001'),'failed checkout rolls back');
o:=checkout(d,'[{"id":"00000000-0000-4000-8000-000000000001","quantity":2}]','receipt-test');oid:=(o->>'id')::uuid;perform pg_temp.assert(checkout(d,'[{"id":"00000000-0000-4000-8000-000000000001","quantity":2}]','receipt-test')=o,'checkout retry is idempotent');perform pg_temp.assert((select stock=stock_before-2 from products where id='00000000-0000-4000-8000-000000000001'),'stock reserved');perform pg_temp.assert((select product_subtotal=2400 from orders where id=oid),'server prices');perform transition_order(oid,'cancelled',actor,'Customer cancellation');perform transition_order(oid,'cancelled',actor,'Duplicate request');perform pg_temp.assert((select stock=stock_before from products where id='00000000-0000-4000-8000-000000000001'),'cancellation restores stock exactly once');
insert into ingredients(name,unit,stock,average_unit_cost) values('Test flour','kg',10,100) returning id into ing;
perform record_purchase(jsonb_build_object('ingredient_id',ing,'quantity',10,'unit_cost',200,'date',current_date),actor);perform pg_temp.assert((select stock=20 and average_unit_cost=150 from ingredients where id=ing),'weighted inventory cost');perform pg_temp.assert((select count(*)=1 from inventory_movements where ingredient_id=ing),'purchase movement audit');
failed:=false;begin perform adjust_inventory(jsonb_build_object('ingredient_id',ing,'quantity_change',-21,'reason','test'),actor);exception when others then failed:=true;end;perform pg_temp.assert(failed,'stock cannot go negative');perform pg_temp.assert((select stock=20 from ingredients where id=ing),'failed adjustment rolls back');
d:=jsonb_set(d,'{phone}','"923009999998"');req:=submit_request(d,'reject-request');
q:=create_quote(jsonb_build_object('request_id',req->>'id','price',5000,'delivery_fee',0,'discount',0,'advance',2500,'notes','Test','feasible',true,'suggested_changes','','expires_at',now()+interval '1 day','status','sent'),'rejected-token');
perform review_request((req->>'id')::uuid,'rejected','Date unavailable',actor);
failed:=false;begin perform decide_quote('rejected-token','accepted');exception when others then failed:=true;end;perform pg_temp.assert(failed,'rejected inquiry cannot accept old quotation');
for n in 1..15 loop perform pg_temp.assert(rate_limit('test-ip'),'rate limit allows normal use');end loop;perform pg_temp.assert(not rate_limit('test-ip'),'rate limit blocks repeated submissions');
end $$;
select pg_temp.assert((dashboard_snapshot(date_trunc('month',now() at time zone 'Asia/Karachi')::date)->>'cake')::numeric=(select coalesce(sum(product_subtotal-discount),0) from orders where status='completed'),'dashboard revenue uses completed orders');
select pg_temp.assert((select sum(order_count) from customer_summaries(array(select id from customers)))=(select count(*) from orders),'customer summaries count all orders');
select pg_temp.assert(not has_function_privilege('anon','public.dashboard_snapshot(date)','EXECUTE'),'dashboard RPC is private');
select pg_temp.assert(not has_function_privilege('authenticated','public.customer_summaries(uuid[])','EXECUTE'),'customer summaries RPC is private');
set local role anon;
select pg_temp.assert((select count(*)=0 from customers),'anon cannot list customers');
select pg_temp.assert((select count(*)=0 from orders),'anon cannot list orders');
select pg_temp.assert((select count(*)=0 from payments),'anon cannot list payments');
select pg_temp.assert((select count(*)>0 from products where active),'anon can view active products');
select pg_temp.assert(not has_function_privilege('anon','public.checkout(jsonb,jsonb,text)','EXECUTE'),'anon cannot bypass checkout endpoint');
select pg_temp.assert(not has_function_privilege('authenticated','public.verify_payment(uuid,uuid)','EXECUTE'),'authenticated cannot directly verify payment');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',true);
select pg_temp.assert((select count(*)=0 from customers),'non-admin cannot read private customers');
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
select pg_temp.assert((select count(*)>0 from customers),'admin can read customers');
reset role;
rollback;
\echo 'PASS: request, quote, advance, status history, stock, inventory, rate limiting, RLS and role tests'
